replicaCount: 2

image:
  repository: europe-west1-docker.pkg.dev/PROJECT_ID/dev-app-repo/webapp
  tag: "1.1.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
