name: CI/CD Dev Webapp

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'charts/webapp/**'

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${GCP_REGION}-docker.pkg.dev

    - name: Build Docker image
      run: |
        TIMESTAMP=$(date +%s)
        IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dev-app-repo/webapp:${TIMESTAMP}"
        docker build -t $IMAGE ./app
        docker push $IMAGE
        echo "IMAGE_TAG=$TIMESTAMP" >> $GITHUB_ENV

    - name: Update Helm values with new tag
      run: |
        yq e '.image.tag = env(IMAGE_TAG)' -i charts/webapp/values.yaml
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add charts/webapp/values.yaml
        git commit -m "CI: update image tag to $IMAGE_TAG" || echo "No changes to commit"
        git push

