name: CI/CD Dev Webapp

on:
  push:
    branches:
      - main
    paths:
      - 'apps/webapp**'
      - 'charts/webapp/**'

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up GCP
      uses: google-github-actions/setup-gcloud@v1
      with:
      project_id: ${{ secrets.GCP_PROJECT_ID }}
      install_components: 'gke-gcloud-auth-plugin'

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        TIMESTAMP=$(date +%s)
        IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dev-app-repo/webapp:${TIMESTAMP}"
        docker build -t $IMAGE ./apps/webapp
        docker push $IMAGE
        echo "IMAGE_TAG=$TIMESTAMP" >> $GITHUB_ENV

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet


    - name: Update Helm values with new tag
      run: |
        yq e '.image.tag = env(IMAGE_TAG)' -i charts/webapp/values.yaml
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add charts/webapp/values.yaml
        git commit -m "CI: update image tag to $IMAGE_TAG" || echo "No changes to commit"
        git push

